<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120827154612 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        // This is probably an abonination
        $this->addSql('INSERT INTO `fos_user_user` VALUES (1,\'demo\',\'demo\',\'demo@example.com\',\'demo@example.com\',1,\'l0gwkg7ajrk8gkwoskww80okwcogs4w\',\'rLi69+GYngVG0XEsCgHA0Y3ib7EnE6hPHZyJ6Qf1skBpNT5KgPDFcgJ+4rYL9zVbv57sVq/+FOsezTHnbUMZzQ==\',NULL,0,0,NULL,NULL,NULL,\'a:1:{i:0;s:16:\"ROLE_SUPER_ADMIN\";}\',0,NULL,\'2012-08-26 22:33:07\',\'2012-08-26 22:33:15\',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,\'null\',NULL,NULL,\'null\',NULL,NULL,\'null\',NULL,NULL);');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DELETE FROM `fos_user_user` where username='demo'");
    }
}
